server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      cookie:
        secure: true         # HTTPS 요청에서만 쿠키 허용
        same-site: None      # SameSite=None 설정

spring:
  application:
    name: ajoufinder

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PW_DEV}

springdoc:
  swagger-ui:
    with-credentials: true