name: Docker CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (without test)
        run: ./gradlew bootJar -x test

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ajoufinder:latest


      - name: SSH to server and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/ajoufinder:latest
            docker stop ajoufinder || true
            docker rm ajoufinder || true
            docker image prune -af
            docker run -d -p 8080:8080 \
              --restart unless-stopped \
              --name ajoufinder \
              -e DB_URL_DEV="${{ secrets.DB_URL_DEV }}" \
              -e DB_USERNAME_DEV="${{ secrets.DB_USERNAME_DEV }}" \
              -e DB_PW_DEV="${{ secrets.DB_PW_DEV }}" \
              ${{ secrets.DOCKER_USERNAME }}/ajoufinder:latest